# Generated by Django 4.0.6 on 2022-08-05 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_emp_hiretime'),
    ]

    operations = [
        migrations.CreateModel(
            name='niceNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=11, verbose_name='靓号')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('level', models.SmallIntegerField(choices=[(1, '普通靓号'), (2, '高级靓号'), (3, '极品靓号')], default=1, verbose_name='靓号级别')),
                ('status', models.SmallIntegerField(choices=[(1, '未占用'), (2, '已占用')], default=2, verbose_name='状态')),
            ],
        ),
        migrations.AlterField(
            model_name='emp',
            name='deptno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', verbose_name='部门'),
        ),
    ]
